version: "3.1"
services:
  db:
    image: postgres:alpine
    environment: 
      POSTGRES_PASSWORD: "1"
      POSTGRES_USER: "root"
      POSTGRES_DB: "intouch"
    ports:
      - 5432:5432
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  node:
    image: node:alpine
    working_dir: /opt
    depends_on:
      - redis
      - db
    volumes:
      - .:/opt
    ports:
      - 3001:3001
    command: node dist/server.js