version: "3.1"
services:
  db:
    image: postgres:alpine
    environment: 
      POSTGRES_PASSWORD: "1"
      POSTGRES_USER: "root"
    ports:
      - 5432:5432
  redis:
    image: redis:alpine
    ports:
      - 6379:6379